url: https://y7kim.github.io
baseurl: /portfolio

# Site settings
title: "Maminiaina - Expert Google Ads"
email: ads.yourtargetagency@gmail.com
description: "Je suis un expert Google Ads et je vous aide à optimiser vos campagnes publicitaires pour maximiser votre ROI."

# Team names, titles and social links
people:
- name: Maminiaina Randriantsoa
  pic: 1
  position: Expert Google Ads
  social:
    - title: twitter
      url: # (Ajouter ton lien Twitter ici)
    - title: linkedin
      url: # (Ajouter ton lien LinkedIn ici)
    - title: facebook
      url: # (Ajouter ton lien Facebook ici)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/votrecompte
  - title: linkedin
    url: https://www.linkedin.com/in/votreprofil
  - title: facebook
    url: http://facebook.com/votrecompte
  - title: github
    url: http://github.com/votrecompte

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
